<?php

namespace Database\Seeders;

use App\Models\SubService;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        SubService::create([
            'id' => 1,
            'service_id' => 1,
            'title_en' => 'Cooling and freezing rooms',
            'desc_en' => 'Cold and freezing rooms are facilities specially designed to maintain low temperatures for the preservation of food, medicines, and temperature-sensitive products. These rooms are widely used in food industries, logistics warehouses, hospitals, and laboratories.',
            'title_ar' => 'غرف التبريد والتجميد',
            'desc_ar' => 'غرف التبريد والتجميد هي منشآت مصممة خصيصًا للحفاظ على درجة حرارة منخفضة لحفظ المواد الغذائية، الأدوية، والمنتجات الحساسة للحرارة. تُستخدم هذه الغرف على نطاق واسع في الصناعات الغذائية، والمستودعات اللوجستية، والمستشفيات، والمختبرات.',
            'image' => 'sub_services/HIlkXR9LR9oTAfjOpIzLQMXYJ6UuAVvXzeFU7KrQ.jpg',
            'created_at' => '2025-02-21 05:27:26',
            'updated_at' => '2025-02-21 05:27:26',
        ]);
        SubService::create([
            'id' => 2,
            'service_id' => 1,
            'title_en' => 'Central air conditioning',
            'desc_en' => 'Central air conditioning is an integrated cooling system used to cool large buildings such as hotels, malls, hospitals, factories, and residential buildings. This system is characterized by its ability to distribute cold air evenly through a network of ducts connected to a main air conditioning unit.',
            'title_ar' => 'التكييف المركزى',
            'desc_ar' => 'التكييف المركزي هو نظام تبريد متكامل يُستخدم لتبريد المباني الكبيرة مثل الفنادق، المولات، المستشفيات، المصانع، والمباني السكنية. يتميز هذا النظام بقدرته على توزيع الهواء البارد بشكل متساوٍ عبر شبكة من القنوات (Ducts) المتصلة بوحدة تكييف رئيسية.',
            'image' => 'sub_services/UX8ARbL828WTIcu3n9R4tTvj9N9PwviIcm8KEjAi.jpg',
            'created_at' => '2025-02-21 05:31:28',
            'updated_at' => '2025-02-21 05:31:28',
        ]);
        SubService::create([
            'id' => 3,
            'service_id' => 1,
            'title_en' => 'Chillers',
            'desc_en' => 'Chiller is a central cooling system that relies on cooling water and then pumping it to indoor units to cool the air in large buildings such as hospitals, factories, malls, and hotels. This system is characterized by its high cooling efficiency and energy saving compared to traditional air conditioning systems.',
            'title_ar' => 'الشيلرات',
            'desc_ar' => 'الشيلر هو نظام تبريد مركزي يعتمد على تبريد الماء ثم ضخه إلى وحدات داخلية لتبريد الهواء في المباني الكبيرة مثل المستشفيات، المصانع، المولات، والفنادق. يتميز هذا النظام بكفاءته العالية في التبريد وتوفير الطاقة مقارنة بأنظمة التكييف التقليدية.',
            'image' => 'sub_services/MtoRQxvfeWdLB56MSMzogpOVcjtb5L4UCMxSt8lp.jpg',
            'created_at' => '2025-02-21 05:34:34',
            'updated_at' => '2025-02-21 05:34:34',
        ]);
        SubService::create([
            'id' => 4,
            'service_id' => 1,
            'title_en' => 'Car cooling',
            'desc_en' => 'The car cooling system is an integrated system responsible for maintaining the engine temperature at the ideal level to prevent overheating that may lead to engine damage. This system relies on circulating coolant through various components to dissipate the heat generated by the combustion of fuel inside the engine.',
            'title_ar' => 'تبريد السيارات',
            'desc_ar' => 'نظام تبريد السيارات هو نظام متكامل مسؤول عن الحفاظ على درجة حرارة المحرك ضمن المستوى المثالي لمنع ارتفاع الحرارة الزائدة التي قد تؤدي إلى تلف المحرك. يعتمد هذا النظام على تدوير سائل التبريد عبر مكونات مختلفة لتبديد الحرارة الناتجة عن احتراق الوقود داخل المحرك.',
            'image' => 'sub_services/rq3JoXKPLwyoeXmBkezkwKNhlScVqQIUSi2KNEPg.jpg',
            'created_at' => '2025-02-21 05:37:22',
            'updated_at' => '2025-02-21 05:37:22',
        ]);
        SubService::create([
            'id' => 5,
            'service_id' => 1,
            'title_en' => 'Kitchen equipment maintenance',
            'desc_en' => 'Kitchen equipment maintenance is the process of periodically inspecting and repairing appliances and tools used in commercial or home kitchens to ensure their efficient performance, safe operation, and extended life. Maintenance includes cooking, refrigeration, ventilation, and preparation and cleaning equipment.',
            'title_ar' => 'صيانة معدات المطابخ',
            'desc_ar' => 'صيانة معدات المطابخ هي عملية الفحص والإصلاح الدوري للأجهزة والأدوات المستخدمة في المطابخ التجارية أو المنزلية لضمان أدائها الفعّال، وسلامة التشغيل، وإطالة عمرها الافتراضي. تشمل الصيانة معدات الطهي، التبريد، التهوية، وأدوات التحضير والتنظيف.',
            'image' => 'sub_services/j8HCZAdvSIduoSyswduG6xIb2b4jtUFfXhtNfhqe.jpg',
            'created_at' => '2025-02-21 05:39:53',
            'updated_at' => '2025-02-21 05:39:53',
        ]);
        SubService::create([
            'id' => 6,
            'service_id' => 2,
            'title_en' => 'General contracting',
            'desc_en' => 'The general contracting sector is the sector responsible for implementing construction and infrastructure projects, including the design, construction, and equipping of residential, commercial, industrial, and public facilities buildings. The sector is characterized by providing integrated services starting from planning and design to implementation and maintenance, while adhering to engineering and quality standards.',
            'title_ar' => 'المقاولات العامة',
            'desc_ar' => 'قطاع المقاولات العامة هو القطاع المسؤول عن تنفيذ المشاريع الإنشائية والبنية التحتية، ويشمل تصميم، بناء، وتجهيز المباني السكنية، التجارية، الصناعية، والمرافق العامة. يتميز القطاع بتقديم خدمات متكاملة بدءًا من التخطيط والتصميم وحتى التنفيذ والصيانة، مع الالتزام بالمعايير الهندسية والجودة.',
            'image' => 'sub_services/5mN2tOrMPy2i8DTZEGj4INYOveCw69JguJVpO15n.jpg',
            'created_at' => '2025-02-21 10:25:36',
            'updated_at' => '2025-02-21 10:25:36',
        ]);
        SubService::create([
            'id' => 7,
            'service_id' => 2,
            'title_en' => 'Interior design and decoration',
            'desc_en' => 'Interior design and decoration is the art and science of enhancing interior spaces to make them more beautiful, comfortable, and functional, in line with the needs of users. It includes the selection of colors, furniture, lighting, materials, and finishes to ensure a harmonious and comfortable environment whether in homes, offices, hotels, or commercial spaces.',
            'title_ar' => 'التصميم الداخلي والديكور',
            'desc_ar' => 'التصميم الداخلي والديكور هو فن وعلم تحسين المساحات الداخلية لجعلها أكثر جمالًا، راحة، ووظيفية، بما يتناسب مع احتياجات المستخدمين. يشمل اختيار الألوان، الأثاث، الإضاءة، المواد، والتشطيبات لضمان بيئة متناسقة ومريحة سواء في المنازل، المكاتب، الفنادق، أو الأماكن التجارية.',
            'image' => 'sub_services/b33YG46MKdfOSVZEgUgVSvURiHTrNy1TWZvDmv0x.jpg',
            'created_at' => '2025-02-21 10:28:06',
            'updated_at' => '2025-02-21 10:28:06',
        ]);
        SubService::create([
            'id' => 8,
            'service_id' => 2,
            'title_en' => 'Finishing works',
            'desc_en' => 'Finishing works are the final stage in construction projects that involves transforming the raw structural structure into a space ready for residential or commercial use. These works include all the fine details that add beauty, comfort and integrated functionality to the place, making it aesthetically and practically harmonious.',
            'title_ar' => 'أعمال التشطيبات',
            'desc_ar' => 'أعمال التشطيبات هي المرحلة النهائية في مشاريع البناء تُعنى تحويل الهيكل الإنشائي الخام إلى مساحة جاهزة للسكن أو الاستخدام التجاري. تشمل هذه الأعمال جميع التفاصيل الدقيقة التي تضفي على المكان جمالاً، راحة ووظائف متكاملة، مما يجعله متناسقًا من الناحية الجمالية والعملية.',
            'image' => 'sub_services/8QdQRlrK9zXWdk2eVUcv1byY0JOL02aemPBjOzFl.jpg',
            'created_at' => '2025-02-21 10:30:42',
            'updated_at' => '2025-02-21 10:30:42',
        ]);
        SubService::create([
            'id' => 9,
            'service_id' => 3,
            'title_en' => 'Real estate investment and development',
            'desc_en' => 'Real estate investment and development is a vital economic sector that involves the purchase, sale, leasing, and development of residential, commercial, and industrial properties with the aim of achieving long-term financial returns. This sector relies on market analysis, strategic location selection, and real estate project management to ensure the highest value for the property.',
            'title_ar' => 'الاستثمار والتطوير العقاري',
            'desc_ar' => 'الاستثمار والتطوير العقاري هو قطاع اقتصادي حيوي يشمل شراء، بيع، تأجير، وتطوير العقارات السكنية والتجارية والصناعية بهدف تحقيق عوائد مالية طويلة الأجل. يعتمد هذا القطاع على تحليل السوق، اختيار المواقع الاستراتيجية، وإدارة المشاريع العقارية لضمان تحقيق أعلى قيمة للممتلكات.',
            'image' => 'sub_services/IiqvMOZtMTVBwJHeZo0Clm1pfEtsoz1887bYKHWf.jpg',
            'created_at' => '2025-02-21 10:34:34',
            'updated_at' => '2025-02-21 10:34:34',
        ]);
        SubService::create([
            'id' => 10,
            'service_id' => 3,
            'title_en' => 'Providing rental storage solutions',
            'desc_en' => 'Providing rental storage solutions means renting warehouses and storage facilities to companies and individuals for specific periods, where these warehouses are equipped with cooling and freezing systems to preserve perishable products such as food, medicines, and medical preparations.',
            'title_ar' => 'توفير حلول التخزين الايجارية',
            'desc_ar' => 'توفير حلول التخزين الإيجارية يعني تأجير المستودعات والمرافق التخزينية للشركات والأفراد لفترات محددة، حيث تكون هذه المستودعات مجهزة بأنظمة تبريد وتجميد للحفاظ على المنتجات القابلة للتلف مثل الأغذية، الأدوية، والمستحضرات الطبية.',
            'image' => 'sub_services/Lz5F5pd1N60wPNPQH3SP5IgCQDK9paligdQDgviV.jpg',
            'created_at' => '2025-02-21 10:38:40',
            'updated_at' => '2025-02-21 10:38:40',
        ]);
        SubService::create([
            'id' => 11,
            'service_id' => 3,
            'title_en' => 'Providing solutions for refrigerated transport',
            'desc_en' => 'Refrigerated truck rental is a flexible logistics solution that allows companies and individuals to rent trucks, vans, or vans equipped with refrigeration and freezing systems to transport perishable products such as food, medicines, and medical supplies in a safe and efficient manner.',
            'title_ar' => 'توفير الحلول الآية جاري للنقل المبرد',
            'desc_ar' => 'تأجير السيارات المبردة هو حل لوجستي مرن يتيح للشركات والأفراد استئجار شاحنات، فان، أو سيارات نقل مزودة بأنظمة تبريد وتجميد لنقل المنتجات القابلة للتلف مثل الأغذية، الأدوية، والمستلزمات الطبية بطريقة آمنة وفعالة.',
            'image' => 'sub_services/IDY4Utw4nmQaCeleLXb0BYrkmTOeD61dmFLAi7Rg.jpg',
            'created_at' => '2025-02-21 10:42:38',
            'updated_at' => '2025-02-21 10:42:38',
        ]);
        SubService::create([
            'id' => 12,
            'service_id' => 4,
            'title_en' => 'Providing cooked and uncooked food',
            'desc_en' => 'Providing catering services includes preparing and delivering cooked meals and uncooked food items to various sectors such as companies, hospitals, schools, factories, camps, and hotels. This solution aims to provide integrated nutrition according to the highest standards of quality and food safety.',
            'title_ar' => 'توفير الإعاشة المطهية والغير مطهية',
            'desc_ar' => 'توفير خدمات الإعاشة يشمل تحضير وتوصيل الوجبات المطهية والمواد الغذائية غير المطهية لقطاعات مختلفة مثل الشركات، المستشفيات، المدارس، المصانع، المعسكرات، والفنادق. يهدف هذا الحل إلى توفير التغذية المتكاملة وفق أعلى معايير الجودة والسلامة الغذائية.',
            'image' => 'sub_services/ctmxN0c31FcgkbZ8DUFgvTK09vGrZyW4hFSOoRsB.jpg',
            'created_at' => '2025-02-21 10:45:45',
            'updated_at' => '2025-02-21 10:45:45',
        ]);
        SubService::create([
            'id' => 13,
            'service_id' => 4,
            'title_en' => 'Supply of food supplies for sustenance',
            'desc_en' => 'Food catering is the provision and distribution of basic food and catering supplies to restaurants, hotels, hospitals, businesses, camps, and schools. This service includes fresh, frozen, and canned products, ensuring compliance with the highest standards of quality, hygiene, and food safety.',
            'title_ar' => 'توريد المواد الغذائية للإعاشة',
            'desc_ar' => 'توريد المواد الغذائية للإعاشة هو توفير وتوزيع المواد الغذائية الأساسية والمستلزمات التموينية إلى المطاعم، الفنادق، المستشفيات، الشركات، المعسكرات، والمدارس. تشمل هذه الخدمة المنتجات الطازجة، المجمدة، والمعلبة، مع ضمان الامتثال لأعلى معايير الجودة، النظافة، وسلامة الغذاء.',
            'image' => 'sub_services/AOsUvjwx3Dey49vmkWQbn9WAuU73ceHORFmgjBW5.jpg',
            'created_at' => '2025-02-21 10:49:13',
            'updated_at' => '2025-02-21 10:49:13',
        ]);
        SubService::create([
            'id' => 14,
            'service_id' => 5,
            'title_en' => 'Management Consulting',
            'desc_en' => 'Management consulting is a specialized service provided by companies or experts to help organizations and companies improve their performance, develop their strategies, and achieve their organizational and operational goals. These consultancies include restructuring, process improvement, human resource management, strategic planning, and digital transformation.',
            'title_ar' => 'الإستشارات الإدارية',
            'desc_ar' => 'الاستشارات الإدارية هي خدمات متخصصة تقدمها شركات أو خبراء لمساعدة المؤسسات والشركات في تحسين أدائها، تطوير استراتيجياتها، وتحقيق أهدافها التنظيمية والتشغيلية. تشمل هذه الاستشارات إعادة الهيكلة، تحسين العمليات، إدارة الموارد البشرية، التخطيط الاستراتيجي، والتحول الرقمي.',
            'image' => 'sub_services/5gCgGwEN6OJNwNmGmdp40Y0pzEAfJK4nVpejhUS5.jpg',
            'created_at' => '2025-02-21 10:52:38',
            'updated_at' => '2025-02-21 10:52:38',
        ]);
        SubService::create([
            'id' => 15,
            'service_id' => 5,
            'title_en' => 'Feasibility studies for projects',
            'desc_en' => 'A feasibility study is a comprehensive analysis to evaluate the financial, marketing, technical, and administrative viability of a new project or expansion of an existing one. This study helps investors and business owners make informed decisions and reduce financial and operational risks.',
            'title_ar' => 'دراسات الجدوي للمشاريع',
            'desc_ar' => 'دراسة الجدوى هي تحليل شامل لتقييم إمكانية نجاح مشروع جديد أو توسعة مشروع قائم من الناحية المالية، التسويقية، الفنية، والإدارية. تساعد هذه الدراسة المستثمرين وأصحاب الأعمال على اتخاذ قرارات مستنيرة وتقليل المخاطر المالية والتشغيلية.',
            'image' => 'sub_services/t31KjYT1SWoQvTatM8yUfcD0RHmnRZsY822yGyQp.jpg',
            'created_at' => '2025-02-21 10:55:27',
            'updated_at' => '2025-02-21 10:55:27',
        ]);
    }
}
